version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    env_file: .env
    networks:
      - backend

  memgraph:
    image: memgraph/memgraph-platform
    env_file: .env
    #ports:
    #  - "127.0.0.1:7687:7687"  # доступ только с localhost
    #  - "127.0.0.1:3000:3000"

    networks:
      - backend
    volumes:
      - memgraph_data:/var/lib/memgraph

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    working_dir: /app/backend
    command: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers=4 --threads=2 --timeout=120
    env_file: .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    #ports:
    #  - "8000:8000"
    depends_on:
      - postgres
      - redis
      - memgraph
    networks:
      - backend

  celery_worker:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    working_dir: /app/backend
    command: celery -A backend.tasks worker --loglevel=info
    env_file: .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - backend
      - redis
    volumes:
      - .:/app
    networks:
      - backend

  frontend:
    build: ./frontend
    env_file: .env
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    #ports:
    #  - "8501:8501"
    depends_on:
      - backend
    networks:
      - backend

  nginx:
    image: nginx:stable
    env_file:
      - .env
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
      - "7687:7687"
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    depends_on:
      - frontend
    networks:
      - backend

volumes:
  pgdata:
  memgraph_data:

networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
